-
  casename: login1
  method: post
  apiname : login
  data: {"username":"admin","password":"123456" }
  extract: {"exToken":"token","message":"msg"}
  duanyan: {"info":{'name': 'admin'}}
  headers:
-
  casename: login2
  method: post
  apiname : login
  data: {"username":"admin","password":"12345678" }
  extract:
  duanyan: {"msg": "用户名或密码错误"}
  headers:

-
  casename: biaodan
  method: post
  apiname : userInfo
  data: {"userid":"1"}
  extract:
  duanyan: {"code": "0001"}
  headers: {'Content-Type': 'application/x-www-form-urlencoded'}


-
  casename: login3
  method: post
  apiname : login
  data: {"username":"admin111","password":"123456" }
  extract:
  duanyan: {"msg": "用户名或密码错误"}
  headers:
